## This file provides two functions that cache the inverse
## of a matrix.

## This function returns a closure where the input matrix x
## and the inverse of x can be stored.
makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    set <- function(y) {
        x <<- y
        i <<- NULL
    }
    get <- function() x
    setsolve <- function(solve) i <<- solve
    getsolve <- function() i
    list(set = set, get = get,
         setsolve = setsolve,
         getsolve = getsolve)
}


## This function takes as input a closure x generated by
## makeCacheMatrix() and either returns the cached inverse
## or calculates, caches, and returns the inverse of the
## cached matrix.
cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    i <- x$getsolve()
    if(!is.null(i)) {
        message("getting cached data")
        return(i)
    }
    data <- x$get()
    i <- solve(data)
    x$setsolve(i)
    i 
}
